# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0004_auto_20161105_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cclass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
