# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0009_auto_20161112_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaign',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_dming', to='stally.Player', verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='character',
            name='cclass',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_nr',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Pokédex number'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_p',
            field=models.CharField(max_length=200, verbose_name='Type'),
        ),
    ]
