# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0011_auto_20170118_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stally.Character')),
            ],
            options={
                'abstract': False,
            },
            bases=('stally.character',),
        ),
        migrations.CreateModel(
            name='Pokemon_new',
            fields=[
                ('trainee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stally.Trainee')),
                ('pokedex_nr', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Pokédex number')),
                ('type_p', models.CharField(max_length=200, verbose_name='Type')),
                ('nature', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['name'],
            },
            bases=('stally.trainee',),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='stally.Character'),
        ),
    ]
