# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def move_pokemons(apps, schema_editor):
        Pokemon = apps.get_model('stally', 'Pokemon')
        Pokemon_new = apps.get_model('stally', 'Pokemon_new')

        for pokemon in Pokemon.objects.all():
            Pokemon_new.objects.create(
                name=pokemon.name,
                image=pokemon.image,
                player=pokemon.player,
                pronouns=pokemon.pronouns,
                cclass=pokemon.cclass,
                description=pokemon.description,
                campaign=pokemon.campaign,
                trainer=pokemon.trainer,
                pokedex_nr=pokemon.pokedex_nr,
                type_p=pokemon.type_p,
                nature=pokemon.nature,
                kind=pokemon.kind
            )

    dependencies = [
        ('stally', '0012_auto_20170124_1520'),
    ]

    operations = [
        migrations.RunPython(move_pokemons),
    ]
