# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0013_auto_20170124_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='character_ptr',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='trainer',
        ),
        migrations.AlterModelOptions(
            name='pokemon_new',
            options={'ordering': ['name'], 'verbose_name': 'Pokémon_new', 'verbose_name_plural': 'Pokémon_new'},
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
