# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0014_auto_20170124_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon_new',
            new_name='Pokemon',
        ),
    ]
