# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0016_auto_20170126_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_playlist',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube playlist'),
        ),
        migrations.AddField(
            model_name='session',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
