# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0017_auto_20170201_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='cclass',
            new_name='character_class',
        ),
    ]
