# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0019_auto_20170201_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='lives_in',
            field=models.ManyToManyField(blank=True, related_name='citizens', to='stally.Place'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players_present',
            field=models.ManyToManyField(blank=True, to='stally.Player'),
        ),
        migrations.AddField(
            model_name='session',
            name='youtube_videos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='stally.URL'),
            preserve_default=False,
        ),
    ]
