# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import stally.myFields


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0022_auto_20170202_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule',
            field=stally.myFields.DayOfTheWeekField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, null=True, verbose_name='Is played on'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_rythm',
            field=models.CharField(blank=True, choices=[(1, 'weekly'), (2, 'biweekly'), (3, 'every three weeks')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='streaming_channel',
            field=models.URLField(blank=True, null=True, verbose_name='Streamed on'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
