# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0026_campaign_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True, verbose_name='At'),
        ),
    ]
