# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20161105_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
