# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_pokemon_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='database.Character'),
        ),
    ]
