# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_character_cclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
