# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20161112_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_nr',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
