# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-12 21:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20161112_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_nr',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
