# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20170201_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lives_in',
            field=models.ManyToManyField(related_name='citizens', to='database.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='campaigns',
            field=models.ManyToManyField(to='database.Campaign'),
        ),
        migrations.AddField(
            model_name='session',
            name='players_present',
            field=models.ManyToManyField(blank=True, null=True, to='database.Player'),
        ),
    ]
