# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20170201_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_dming', to='database.Player', verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='database.Campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='in_campaign_since',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Session'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='database.Player'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='database.Character'),
        ),
    ]
