# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20170202_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='youtube_videos',
        ),
        migrations.AddField(
            model_name='url',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='database.Session'),
            preserve_default=False,
        ),
    ]
