# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20170310_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
