# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0003_auto_20161029_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stally.Player'),
        ),
    ]
