# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0004_campaign_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stally.Player'),
        ),
    ]
