# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0005_auto_20161030_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
