# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0006_auto_20161030_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='trainer',
        ),
    ]
