# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0007_remove_character_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stally.Character')),
            ],
            bases=('stally.character',),
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('trainee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stally.Trainee')),
                ('type_p', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
            ],
            bases=('stally.trainee',),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='stally.Character'),
        ),
    ]
