# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0008_auto_20161030_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_dming', to='stally.Player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stally.Campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stally.Player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stally.Campaign'),
        ),
    ]
