# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0009_auto_20161030_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='character_ptr',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='trainee_ptr',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='character_ptr',
            field=models.OneToOneField(auto_created=True, default='bla', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stally.Character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(default='bla', on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='stally.Character'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
    ]
